// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type ExperienceDocumentDataSlicesSlice = EXsSlice

/**
 * Content for Experience documents
 */
interface ExperienceDocumentData {
  /**
   * Slice Zone field in *Experience*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperienceDocumentDataSlicesSlice>
}

/**
 * Experience document from Prismic
 *
 * - **API ID**: `experience`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ExperienceDocumentData>,
    'experience',
    Lang
  >

type HomeDocumentDataSlicesSlice = never

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * About field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField

  /**
   * Available field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  available: prismic.BooleanField

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

type WorkDocumentDataSlicesSlice =
  | TextSlice
  | ImageTwoColumnSlice
  | ImagewithCaptionSlice

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Work Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.work_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_title: prismic.KeyTextField

  /**
   * Work Year field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.work_year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_year: prismic.KeyTextField

  /**
   * featuredImage field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.featuredimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredimage: prismic.ImageField<never>

  /**
   * Services Provided field in *Work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.services_provided
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  services_provided: prismic.RichTextField

  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: work.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: work.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, 'work', Lang>

export type AllDocumentTypes = ExperienceDocument | HomeDocument | WorkDocument

/**
 * Primary content in *EXs → Base → Primary*
 */
export interface EXsSliceDefaultPrimary {
  /**
   * work field in *EXs → Base → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: e_xs.default.primary.work
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work: prismic.KeyTextField

  /**
   * year field in *EXs → Base → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: e_xs.default.primary.year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField

  /**
   * till-year field in *EXs → Base → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: e_xs.default.primary.tillyear
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tillyear: prismic.KeyTextField
}

/**
 * Base variation for EXs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EXsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EXsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *EXs*
 */
type EXsSliceVariation = EXsSliceDefault

/**
 * EXs Shared Slice
 *
 * - **API ID**: `e_xs`
 * - **Description**: EXs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EXsSlice = prismic.SharedSlice<'e_xs', EXsSliceVariation>

/**
 * Primary content in *ImageTwoColumn → Default → Primary*
 */
export interface ImageTwoColumnSliceDefaultPrimary {
  /**
   * Image One field in *ImageTwoColumn → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_two_column.default.primary.image_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_one: prismic.ImageField<never>

  /**
   * Image Two field in *ImageTwoColumn → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_two_column.default.primary.image_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_two: prismic.ImageField<never>

  /**
   * Caption (optional) field in *ImageTwoColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_two_column.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField
}

/**
 * Default variation for ImageTwoColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTwoColumnSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageTwoColumnSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ImageTwoColumn*
 */
type ImageTwoColumnSliceVariation = ImageTwoColumnSliceDefault

/**
 * ImageTwoColumn Shared Slice
 *
 * - **API ID**: `image_two_column`
 * - **Description**: ImageTwoColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTwoColumnSlice = prismic.SharedSlice<
  'image_two_column',
  ImageTwoColumnSliceVariation
>

/**
 * Primary content in *ImagewithCaption → Default → Primary*
 */
export interface ImagewithCaptionSliceDefaultPrimary {
  /**
   * WorkImage field in *ImagewithCaption → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: imagewith_caption.default.primary.workimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  workimage: prismic.ImageField<never>

  /**
   * Caption (optional) field in *ImagewithCaption → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: imagewith_caption.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField
}

/**
 * Default variation for ImagewithCaption Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagewithCaptionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImagewithCaptionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ImagewithCaption*
 */
type ImagewithCaptionSliceVariation = ImagewithCaptionSliceDefault

/**
 * ImagewithCaption Shared Slice
 *
 * - **API ID**: `imagewith_caption`
 * - **Description**: ImagewithCaption
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagewithCaptionSlice = prismic.SharedSlice<
  'imagewith_caption',
  ImagewithCaptionSliceVariation
>

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AllDocumentTypes,
      ExperienceDocument,
      ExperienceDocumentData,
      ExperienceDocumentDataSlicesSlice,
      EXsSlice,
      EXsSliceDefault,
      EXsSliceDefaultPrimary,
      EXsSliceVariation,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ImageTwoColumnSlice,
      ImageTwoColumnSliceDefault,
      ImageTwoColumnSliceDefaultPrimary,
      ImageTwoColumnSliceVariation,
      ImagewithCaptionSlice,
      ImagewithCaptionSliceDefault,
      ImagewithCaptionSliceDefaultPrimary,
      ImagewithCaptionSliceVariation,
      TextSlice,
      TextSliceDefault,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataSlicesSlice
    }
  }
}
