// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  e_xs: dynamic(() => import('./EXs')),
  image_two_column: dynamic(() => import('./ImageTwoColumn')),
  imagewith_caption: dynamic(() => import('./ImagewithCaption')),
  text: dynamic(() => import('./Text'))
}
